version: '3.8'

services:
  apache_cve_box:
    build: .
    container_name: ctf_cve_2021_41773
    ports:
      - "8082:80"
    environment:
      # The flag is hidden on the file system
      FLAG_CONTENT: "FLAG{Ap4ch3_P4th_Trav3rs4l_CVE_2021_41773}"
    restart: always