# docker-compose.yml
version: '3.8'

services:
  linux_pwn_box:
    build: . # Build using the Dockerfile in the current directory
    container_name: ctf_linux_box
    ports:
      - "2222:22" # Map host port 2222 to container SSH port 22
    restart: always